```{r}
library(Seurat)
library(Matrix)
library(dplyr)
library(cowplot)
#library(readxl)

options(bitmapType='cairo') 
prefix = "Myeloid"
infile = "AllCell_Myeloid.rds" ## need to generate this from the AllCell script
source("AuxFunctions.R")
```

```{r}
gbm.combined=readRDS(file=infile)
DefaultAssay(object = gbm.combined) <- "RNA" 

#split the combined object into a list
ob.list1<-SplitObject(gbm.combined,split.by= "orig.ident")

```

## clean the list of genes and cells
```{r}
minCells = 50
maxCells = 3000

ob.list = list()
objectlist = c()
condlist = c()

genesFiltered <- cleanGeneNames(rownames(gbm.combined))

for (i in 1:length(ob.list1)){
    test = ob.list1[[i]]
    test = subset(test, features = genesFiltered)
    dim(test)
    test = subset(test, subset = nFeature_RNA >= 100)
    dim(test)
    
  	if(ncol(test) >= minCells){ 
  	  m = test@meta.data
      print(m$orig.ident[[1]])

  	  test@meta.data = m[,1:12]
  	  test@reductions=list()
  	  test@commands=list()
  	  test@tools=list()
  	  test@assays$integrated=list()
  	  
      if(ncol(test) > maxCells){
        print(ncol(test))
        downsampleCols = sample(colnames(test),maxCells)
        m1 = test@assays$RNA@counts
        m1 = m1[,downsampleCols]
        m1 = m1[rowSums(m1 != 0) >= 5,]

        test = subset(test, cells = downsampleCols, features=rownames(m1))
        test = subset(test, subset = nFeature_RNA >= 100)
      }
      
  	  test <- NormalizeData(object = test, verbose = TRUE)
  	  test  <- FindVariableFeatures(object = test , selection.method = "vst", 
  	                                nfeatures = 3000)    
     	ob.list = append(ob.list,test)
    	objectlist = append(objectlist,m$orig.ident[[1]])
      condlist = append(condlist,as.character(m$condition[[1]]))
  	}
}

cellNumbers = sapply(ob.list, ncol)
table1 = data.frame(ID=objectlist,Cond = condlist, cellNumber = cellNumbers)
write.csv(table1,file=paste(prefix,"cellNumbers.max3000.csv",sep="."))
#saveRDS(ob.list,file=paste(prefix, "ObList.rds", sep="_"))
```

```{r}
ob.list1 = ob.list[c(1:5,14:17,28:32)]
ob.list2 = ob.list[c(6:9,18:22,33:35)]
ob.list3 = ob.list[c(10:13,23:27,36:40)]


k.filterMax <- min(200, min(sapply(ob.list1, ncol)))
anchors1 <- FindIntegrationAnchors(object.list = ob.list1, k.filter = k.filterMax, anchor.features = 3000)
gbm.combined1 <- IntegrateData(anchorset = anchors1)
rm(anchors1)

k.filterMax <- min(200, min(sapply(ob.list2, ncol)))
anchors2 <- FindIntegrationAnchors(object.list = ob.list2, k.filter = k.filterMax, anchor.features = 3000)
gbm.combined2 <- IntegrateData(anchorset = anchors2)
rm(anchors2)

k.filterMax <- min(200, min(sapply(ob.list3, ncol)))
anchors3 <- FindIntegrationAnchors(object.list = ob.list3, k.filter = k.filterMax, anchor.features = 3000)
gbm.combined3 <- IntegrateData(anchorset = anchors3)
rm(anchors3)
ob.list = list(gbm.combined1,gbm.combined2,gbm.combined3)
```

```{r}
k.filterMax <- min(200, min(sapply(ob.list, ncol)))

anchors <- FindIntegrationAnchors(object.list = ob.list, k.filter = k.filterMax, anchor.features = 3000)
saveRDS(anchors,file=paste(prefix, "anchors.rds", sep="_"))
rm(ob.list)
rm(gbm.combined1)
rm(gbm.combined2)
rm(gbm.combined3)
gc()

gbm.combined <- IntegrateData(anchorset = anchors)
DefaultAssay(object = gbm.combined) <- "integrated"
saveRDS(gbm.combined,file=paste(prefix, "integrated.rds", sep="_"))
rm(anchors)
gc()
```

#removing 51 cells with NaN
```{r}
dim(gbm.combined)
cellToRemove <- colnames(gbm.combined@assays$integrated@data)[colSums(is.na(gbm.combined@assays$integrated@data))>0]
ids <- names(Idents(gbm.combined))
gbm.combined <- subset(gbm.combined, cells = ids[!ids %in% cellToRemove])
dim(gbm.combined)

gbm.combined <- ScaleData(object = gbm.combined, verbose = TRUE, vars.to.regress = c("percent.mt","percent.ribo","nFeature_RNA","nCount_RNA","CC.Difference"))
gbm.combined <- RunPCA(object = gbm.combined, npcs = 30, verbose = TRUE)

gbm.combined$condition = factor(gbm.combined$condition,levels=c("GBM.new","GBM.rec","GBM.PD1"))
```

```{r}
minDist = 0.2
spread1 = 5
NN = 30
seedUse = 122
epoch = 1000

gbm.combined <- RunUMAP(object = gbm.combined, reduction = "pca", dims = 1:30,min.dist = minDist, spread=spread1, n.neighbors=NN, seed.use = seedUse, n.epochs=epoch) #, min.dist = 0.1, n.neighbors=10, seed.use = 22, n.epochs=500)

prefix1 = paste(prefix,".MinD",minDist,".sprd",spread1,".NN",NN,".seed",seedUse,".ep",epoch,sep="")

outfile = paste(prefix1,"_UMAP.byBatch.png",sep="")
png(filename = outfile,width = 800, height = 1200)
DimPlot(object = gbm.combined, reduction = "umap", group.by = "condition", pt.size = 1)
dev.off()

outfile = paste(prefix1,"_UMAP.nUMI.png",sep="")
png(filename = outfile,width = 800, height = 800)
FeaturePlot(object = gbm.combined, features = c("nCount_RNA"), min.cutoff = "q9", pt.size = 2) #umi plot
dev.off()

outfile = paste(prefix1,"_UMAP.nGene.png",sep="")
png(filename = outfile,width = 800, height = 800)
FeaturePlot(object = gbm.combined, features = c("nFeature_RNA"), min.cutoff = "q9", pt.size = 2) #umi plot
dev.off()

outfile = paste(prefix1,"_UMAP.treatment.png",sep="")
png(filename = outfile,width = 800, height = 800)
DimPlot(object = gbm.combined, reduction = "umap", split.by = "condition", pt.size = 1, ncol=2)
dev.off()
```

```{r}
DefaultAssay(gbm.combined) <- "integrated"

gbm.combined <- FindNeighbors(object = gbm.combined, reduction = "pca", dims = 1:30, nn.method = "annoy", annoy.metric = "cosine", force.recalc = TRUE)

gbm.combined <- FindClusters(gbm.combined, resolution = 0.3)
gbm.combined$integrated_snn_res.0.3 = factor(gbm.combined$integrated_snn_res.0.3,levels=c(as.character(0:13)))

outfile = paste(prefix,"_UMAP.Res0.3.png",sep="")
png(filename = outfile,width = 800, height = 800)
DimPlot(object = gbm.combined, reduction = "umap", group.by = "integrated_snn_res.0.3", label = TRUE, label.size = 8, pt.size = 1,cols = colors[1:14])
dev.off()

outfile = paste(prefix,"_UMAP.Res0.3.noLabel.png",sep="")
png(filename = outfile,width = 800, height = 800)
DimPlot(object = gbm.combined, reduction = "umap", group.by = "integrated_snn_res.0.3", label = FALSE, label.size = 8, pt.size = 1,cols = colors[1:14])
dev.off()

outfile = paste(prefix,"_UMAP.Res0.3.split.png",sep="")
png(filename = outfile,width = 800, height = 800)
DimPlot(object = gbm.combined, reduction = "umap", split.by = "integrated_snn_res.0.3", label = FALSE, pt.size = 0.5, ncol=3,cols = colors[1:14])
dev.off()

```

Compute cluster markers
```{r}
DefaultAssay(gbm.combined) <- "RNA"
cluster.markers<- FindAllMarkers(object = gbm.combined, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.322)
outfile = paste(prefix,"_ClusterDiffGene.Res0.3.log.322.csv",sep="")
write.csv(cluster.markers, file=outfile)
```

Annotate myeloid cell type
```{r}
Idents(object = gbm.combined) <- "integrated_snn_res.0.3"
current.cluster.ids <- c(0:13)
new.cluster.ids <- c("M1-CCL3-4-IL1B","M2-CXCR4-ZFP36-MHC2Hi","M5-CX3CR1-TMEM119-ADORA3","M7-VCAN-GPNMB-ANGPTL4-GlycoHi","M4-HSPhi","Proliferating","M6-GPNMB-APOE-CD68-Mphage","DC","L+M","Mono-FCN1-S100A8-9-VCAN","LowRead1","M3-ISGhi","Unknown","Unknown")
Idents(object = gbm.combined) <- plyr::mapvalues(x = Idents(object = gbm.combined), from = current.cluster.ids, to = new.cluster.ids)

gbm.combined@meta.data$celltype <- Idents(object = gbm.combined)
gbm.combined@meta.data$celltype <- factor(gbm.combined@meta.data$celltype,
                                         level= c("M1-CCL3-4-IL1B","M2-CXCR4-ZFP36-MHC2Hi",
                                                 "M3-ISGhi","M4-HSPhi",
                                                 "M5-CX3CR1-TMEM119-ADORA3",
                                                 "M6-GPNMB-APOE-CD68-Mphage",
                                                 "M7-VCAN-GPNMB-ANGPTL4-GlycoHi",
                                                 "Mono-FCN1-S100A8-9-VCAN",
                                                 "DC","Proliferating","L+M","LowRead1"))


library(colorspace)
library(scales)
colorsCluster = c(divergingx_hcl(12,palette="RdYlBu"),"black")
colorsCluster[8] <- "pink"
#show_col(colors)
Idents(object = gbm.combined) <- "celltype"
DefaultAssay(gbm.combined) <- "RNA"

outfile = paste(prefix,"_UMAP.byCelltype.png",sep="")
png(filename = outfile,width = 800, height = 800)
DimPlot(object = gbm.combined, reduction = "umap", group.by = "celltype", label = TRUE, label.size = 8, pt.size = 1,cols = colorsCluster)
dev.off()

outfile = paste(prefix,"_UMAP.noLabel.byCelltype.png",sep="")
png(filename = outfile,width = 800, height = 800)
DimPlot(object = gbm.combined, reduction = "umap", group.by = "celltype", label = FALSE, label.size = 8, pt.size = 1,cols = colorsCluster)
dev.off()

#saveRDS(gbm.combined,file=paste(prefix, "res.0.3.withAnnot.rds", sep="_"))
#gbm.combined <- readRDS(file=paste(prefix, "res.0.3.withAnnot.rds", sep="_"))
```

Get DEGs by condition per cluster
```{r}
DefaultAssay(gbm.combined)<-"RNA"
celltypes = c("M1-CCL3-4-IL1B","M2-CXCR4-ZFP36-MHC2Hi","M3-ISGhi","M4-HSPhi","M5-CX3CR1-TMEM119-ADORA3","M6-GPNMB-APOE-CD68-Mphage","M7-VCAN-GPNMB-ANGPTL4-GlycoHi","Mono-FCN1-S100A8-9-VCAN","DC","Proliferating",
"L+M","LowRead1")

i=1
geneSet=c()

for (i in 1:length(celltypes)){
  celltype1 = celltypes[i]
  
  TreatmentSubset = subset(gbm.combined,subset = (celltype == celltype1))
  Idents(object = TreatmentSubset) <- "condition"
  markers <- FindAllMarkers(TreatmentSubset,min.pct = 0.25, logfc.threshold = 0.322,only.pos = T)
  markers <- as.data.frame(markers)
  markers$diff = markers$pct.1 - markers$pct.2
  markers$celltype = celltype1
  geneSet=union(geneSet,rownames(geneSet))
  
  outfile = paste(prefix,"DEG","GBM.byType.log.322.tsv",sep=".")
  write.table(markers, file=outfile, sep="\t", col.names = !file.exists(outfile),append=TRUE)
}

```


## save the Monocytes and DCs for further subclustering
```{r}
ids = rownames(subset(gbm.combined@meta.data,celltype %in% c("DC")))
subsetObject = subset(gbm.combined, cells = ids)
saveRDS(subsetObject,file=paste(prefix, "DC.rds", sep="_"))

ids = rownames(subset(gbm.combined@meta.data,celltype %in% c("Mono-FCN1-S100A8-9-VCAN")))
subsetObject = subset(gbm.combined, cells = ids)
saveRDS(subsetObject,file=paste(prefix, "Mono.rds", sep="_"))

ids = rownames(subset(gbm.combined@meta.data,celltype %in% c("Mono-FCN1-S100A8-9-VCAN","DC")))
subsetObject = subset(gbm.combined, cells = ids)
saveRDS(subsetObject,file=paste(prefix, "MonoAndDC.rds", sep="_"))

table(gbm.combined$celltype)
```

