```{r}
library(Seurat)
library(Matrix)
library(dplyr)
library(cowplot)

options(bitmapType='cairo') 
prefix = "DC"
infile = "Myeloid_DC.rds"
```

```{r}
gbm.combined=readRDS(file=infile)
DefaultAssay(object = gbm.combined) <- "RNA" 

#remove genes that are not expressed by this subset
m1 = gbm.combined@assays$RNA@counts
dim(m1)
m1 = m1[rowSums(m1 != 0) >= 5,]
dim(m1)

gbm.combined = subset(gbm.combined, features=rownames(m1))

#after removal, keep only cells with at least 100 different transcripts
gbm.combined = subset(gbm.combined, subset = nFeature_RNA >= 100)
dim(gbm.combined)

#clear the integrated data and cluster info from the main myeloid analysis
m = gbm.combined@meta.data
gbm.combined@meta.data = m[,1:12]

DefaultAssay(object = gbm.combined) <- "integrated" 
gbm.combined <- RunPCA(object = gbm.combined, npcs = 30, verbose = TRUE)

gbm.combined$condition = factor(gbm.combined$condition,levels=c("GBM.new","GBM.rec","GBM.PD1"))
#saveRDS(gbm.combined,file=paste(prefix, "scaled.PCA.rds", sep="_"))
```


```{r}
minDist = 0.2
spread1 = 10
NN = 30
seedUse = 122
epoch = 1000

gbm.combined <- RunUMAP(object = gbm.combined, reduction = "pca", dims = 1:30,min.dist = minDist, spread=spread1, n.neighbors=NN, seed.use = seedUse, n.epochs=epoch) #, min.dist = 0.1, n.neighbors=10, seed.use = 22, n.epochs=500)

prefix1 = paste(prefix,".MinD",minDist,".sprd",spread1,".NN",NN,".seed",seedUse,".ep",epoch,sep="")

outfile = paste(prefix1,"_UMAP.byBatch.png",sep="")
png(filename = outfile,width = 800, height = 1200)
DimPlot(object = gbm.combined, reduction = "umap", group.by = "condition", pt.size = 1)
dev.off()

outfile = paste(prefix1,"_UMAP.nUMI.png",sep="")
png(filename = outfile,width = 800, height = 800)
FeaturePlot(object = gbm.combined, features = c("nCount_RNA"), min.cutoff = "q9", pt.size = 2) #umi plot
dev.off()

outfile = paste(prefix1,"_UMAP.nGene.png",sep="")
png(filename = outfile,width = 800, height = 800)
FeaturePlot(object = gbm.combined, features = c("nFeature_RNA"), min.cutoff = "q9", pt.size = 2) #umi plot
dev.off()

outfile = paste(prefix1,"_UMAP.treatment.png",sep="")
png(filename = outfile,width = 800, height = 800)
DimPlot(object = gbm.combined, reduction = "umap", split.by = "condition", pt.size = 1, ncol=2)
dev.off()

#saveRDS(gbm.combined,file=paste(prefix1, ".rds", sep="_"))
#gbm.combined <- readRDS(file=paste(prefix1, ".rds", sep="_"))
```

```{r}
outfile = paste(prefix,"_UMAP.MainCellTypes.png",sep="")
png(filename = outfile,width = 1200, height = 800)
FeaturePlot(object = gbm.combined, features = c("HLA-DRA","FCER1A","CD1C","CLEC10A","CLEC9A","IRF8","BATF3","CCR7","LAMP3"), min.cutoff = "q9",  pt.size = 0.5, ncol=3, cols = c("lightgrey","red"))
dev.off()
```

```{r}
DefaultAssay(gbm.combined) <- "integrated"

gbm.combined <- FindNeighbors(object = gbm.combined, reduction = "pca", dims = 1:30, nn.method = "annoy", annoy.metric = "cosine", force.recalc = TRUE)
gbm.combined <- FindClusters(gbm.combined, resolution = 0.8) ##we tested several resolutions
```

Compute cluster marker
```{r}
library(future)
library(future.apply)
plan("multiprocess", workers = 4)
options(future.globals.maxSize = 20 * 1024^3)

Idents(object = gbm.combined) <- "integrated_snn_res.0.8"
cluster.markers<- FindAllMarkers(object = gbm.combined, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.322)
outfile = paste(prefix,"_ClusterDiffGene.Res0.8.logFC.322.csv",sep="")
write.csv(cluster.markers, file=outfile)

```

Annotate cluster
```{r}
Idents(object = gbm.combined) <- "integrated_snn_res.0.8"
current.cluster.ids <- c(0:8)
new.cluster.ids <- c("MonoDC1-CD14-FCER1A-CD1C-CLEC10A","LowReads","MonoDC3-CD16-C1QA-CCL3","MonoDC2-CD16-C1QA-VEGFA-THBS1","MonoDC4-CD14-CD16-CLEC10A","cDC2-CD1C-CLEC10A-LTB-CD52","cDC1-CLEC9A-IRF8-BATF3","mDC-LAMP3-CCR7-CD80","HSPHi-Dying")
Idents(object = gbm.combined) <- plyr::mapvalues(x = Idents(object = gbm.combined), from = current.cluster.ids, to = new.cluster.ids)


###### Percentage of each celltype in each sample ###########################################
gbm.combined@meta.data$celltype <- Idents(object = gbm.combined)
gbm.combined@meta.data$celltype <- factor(gbm.combined@meta.data$celltype, 
                                                 levels = c("cDC2-CD1C-CLEC10A-LTB-CD52","cDC1-CLEC9A-IRF8-BATF3","mDC-LAMP3-CCR7-CD80",
                                                            "MonoDC1-CD14-FCER1A-CD1C-CLEC10A","MonoDC2-CD16-C1QA-VEGFA-THBS1",
                                                            "MonoDC3-CD16-C1QA-CCL3","MonoDC4-CD14-CD16-CLEC10A","LowReads","HSPHi-Dying"))


library(colorspace)
library(scales)

colorsMyeloid = c(divergingx_hcl(12,palette="RdYlBu"),"black")
colorsMphage <- colorsMyeloid[2]
colorsMono <- colorsMyeloid[6]

colorsCluster = sequential_hcl(12,palette="Reds")
colorsCluster = c(colorsCluster[c(1,3,5,7,9,10,11)],"grey50","grey86")
colorsCluster[4] <- "pink"
colorsCluster[6] <- colorsMphage
colorsCluster[5] <- colorsMono
Idents(object = gbm.combined) <- "celltype"
DefaultAssay(gbm.combined) <- "RNA"

outfile = paste(prefix,"_UMAP.Res0.8.byCellType.png",sep="")
png(filename = outfile,width = 800, height = 800)
DimPlot(object = gbm.combined, reduction = "umap", group.by = "celltype", label = TRUE, label.size = 8, pt.size = 2,cols = colorsCluster)
dev.off()

outfile = paste(prefix,"_UMAP.Res0.8.noLabel.byCellType.png",sep="")
png(filename = outfile,width = 800, height = 800)
DimPlot(object = gbm.combined, reduction = "umap", group.by = "celltype", label = FALSE, label.size = 8, pt.size = 2,cols = colorsCluster)
dev.off()

#saveRDS(gbm.combined,file=paste(prefix, "res.0.8.withAnnot.rds", sep="_"))
#gbm.combined <- readRDS(file=paste(prefix, "res.0.8.withAnnot.rds", sep="_"))
```

For suppl table
```{r}
cluster.markers<- FindAllMarkers(object = gbm.combined, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.322)
outfile = paste(prefix,"_ClusterDiffGene.Res0.8.logFC.322.byCelltype.csv",sep="")
write.csv(cluster.markers, file=outfile)
```


## Get DEGs by condition for each clusters
```{r}
DefaultAssay(gbm.combined)<-"RNA"
celltypes = c("cDC2-CD1C-CLEC10A-LTB-CD52","cDC1-CLEC9A-IRF8-BATF3","mDC-LAMP3-CCR7-CD80","MonoDC1-CD14-FCER1A-CD1C-CLEC10A","MonoDC2-CD16-C1QA-VEGFA-THBS1","MonoDC3-CD16-C1QA-CCL3","MonoDC4-CD14-CD16-CLEC10A")
i=1
geneSet=c()

for (i in 1:length(celltypes)){
  celltype1 = celltypes[i]
  
  TreatmentSubset = subset(gbm.combined,subset = (celltype == celltype1))
  Idents(object = TreatmentSubset) <- "condition"
  markers <- FindAllMarkers(TreatmentSubset,min.pct = 0.25, logfc.threshold = 0.585,only.pos = T)
  markers <- as.data.frame(markers)
  markers$diff = markers$pct.1 - markers$pct.2
  markers$celltype = celltype1
  geneSet=union(geneSet,rownames(geneSet))
  
  #outfile = paste(prefix,"DEG",celltype1,".GBM.pembroVsNone.csv",sep=".")
  outfile = paste(prefix,"DEG","GBM.byType.tsv",sep=".")
  write.table(markers, file=outfile, sep="\t", col.names = !file.exists(outfile),append=TRUE)
}
```

