#Initialization
```{r}
library(Seurat)
library(Matrix)
library(dplyr)
library(cowplot)
library(readxl)

rawDataDir = "./"
sampleTable = "SampleList.PBMC.csv"
Path10x = "outs/raw_feature_bc_matrix/"

pctMitoCutoff = 0.2
pctRiboCutoff = 0.4
prefix = "PBMC.all"

s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes
```


#Read the 10x output files
```{r}
dirs <- read.csv(sampleTable,row.names=1)
ID1 = rownames(dirs)

ob.list = list()
objectlist = c()

drawPlot=0

for (i in 1:length(ID1)){
    
  	sampleID <- as.character(dirs[i,2])
  	path1 <- paste(rawDataDir,sampleID,"/",Path10x,sep="")
  	gbm <- Read10X(data.dir=path1) 
  	print(path1)
  	
  	#each feature is supported by a min of 20 cells
    gbm = gbm[rowSums(gbm != 0) >= 20,]
	
    #each cell has at least 200 features
    gbm = gbm[,colSums(gbm != 0) >= 200]
	
	nUMI <- Matrix::colSums(gbm)
	nGene <- Matrix::colSums(gbm != 0)
	mito.genes <- grep(pattern = "^MT-", x = rownames(gbm), value = TRUE)
	percent.mito <- Matrix::colSums(gbm[which(rownames(gbm) %in% mito.genes),])/Matrix::colSums(gbm)
	  
	ribosome.genes <- grep(pattern = "^RP[LS]", x = rownames(gbm), value = TRUE)
	percent.ribo <- Matrix::colSums(gbm[which(rownames(gbm) %in% ribosome.genes),])/Matrix::colSums(gbm)
	
    if(drawPlot==1){
  	    png(paste(sampleID,".UMI.pctMito.png",sep=""))
	    plot(nUMI,percent.mito,xlab="nUMI",ylab="pctMito")
	    dev.off()
	  
	    png(paste(sampleID,".UMI.pctRibo.png",sep=""))
	    plot(nUMI,percent.ribo,xlab="nUMI",ylab="pctRibo")
	    dev.off()
	}
	  
	print(dim(gbm))
  	gbm = gbm[,percent.mito<=pctMitoCutoff & percent.ribo<=pctRiboCutoff] 
	  
	#downsample to max 10,000 cells per sample
	if(ncol(gbm) > 10000){
	    downsampleCols = sample(colnames(gbm),10000)
	    gbm = gbm[,downsampleCols]
	}
	print(dim(gbm))
	  
	gbm.seurat <- CreateSeuratObject(counts = gbm, project = sampleID, min.cells = 20, min.features=200)
	  
	gbm.seurat$ID <- sampleID
	gbm.seurat$condition <- as.character(dirs[i,3])
	gbm.seurat <- PercentageFeatureSet(gbm.seurat, pattern = "^MT-", col.name = "percent.mt")
	gbm.seurat <- PercentageFeatureSet(gbm.seurat, pattern = "^RP[LS]", col.name = "percent.ribo")
	  
	gbm.seurat <- NormalizeData(object = gbm.seurat, verbose = TRUE)
	  
	#We assign scores in the CellCycleScoring function, which stores S and G2/M scores in object meta data, along with the predicted classification of each cell in either G2M, S or G1 phase.
	gbm.seurat <- CellCycleScoring(gbm.seurat, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE) 
	gbm.seurat$CC.Difference <- gbm.seurat$S.Score-gbm.seurat$G2M.Score
	gbm.seurat <- FindVariableFeatures(object = gbm.seurat, selection.method = "vst", nfeatures = 2000)
	
	ob.list = append(ob.list,gbm.seurat)
	objectlist = c(objectlist,sampleID)
	gc()
}

dirs$cellNumbers = sapply(ob.list, ncol)
write.csv(dirs,file=paste(prefix,"cellNumbers.csv",sep="."))
#saveRDS(ob.list,file=paste(prefix, "ObList.rds", sep="_"))

rm(gbm.combined)
rm(ob.list1)
```

```{r}
ob.list1 = ob.list[c(1:3,6:9,14)] #1/2 samples of each condition
ob.list2 = ob.list[c(4:5,10:13,15)] 

library(future)
library(future.apply)
plan("multiprocess", workers = 4)
options(future.globals.maxSize = 20 * 1024^3)

k.filterMax <- min(200, min(sapply(ob.list1, ncol)))
anchors1 <- FindIntegrationAnchors(object.list = ob.list1, k.filter = k.filterMax, anchor.features = 3000)
gbm.combined1 <- IntegrateData(anchorset = anchors1)
rm(anchors1)

k.filterMax <- min(200, min(sapply(ob.list2, ncol)))
anchors2 <- FindIntegrationAnchors(object.list = ob.list2, k.filter = k.filterMax, anchor.features = 3000)
gbm.combined2 <- IntegrateData(anchorset = anchors2)
rm(anchors2)

ob.list = list(gbm.combined1,gbm.combined2)

k.filterMax <- min(200, min(sapply(ob.list, ncol)))

library(future)
library(future.apply)
plan("multiprocess", workers = 4)
options(future.globals.maxSize = 20 * 1024^3)

anchors <- FindIntegrationAnchors(object.list = ob.list, k.filter = k.filterMax, anchor.features = 3000)
#saveRDS(anchors,file=paste(prefix, "anchors.rds", sep="_"))

rm(ob.list)
rm(gbm.combined1)
rm(gbm.combined2)
rm(gbm.combined3)
gc()

plan("multiprocess", workers = 1)
#anchors <- readRDS(file=paste(prefix, "anchors.rds", sep="_"))
gbm.combined <- IntegrateData(anchorset = anchors)
DefaultAssay(object = gbm.combined) <- "integrated"

#saveRDS(gbm.combined,file=paste(prefix, "integrated.rds", sep="_"))

rm(anchors)
gc()
```

#scale data and run PCA
```{r}
plan("multiprocess", workers = 4)
gbm.combined <- ScaleData(object = gbm.combined, verbose = TRUE, vars.to.regress = c("percent.mt","percent.ribo","nFeature_RNA","nCount_RNA","CC.Difference"))
gbm.combined <- RunPCA(object = gbm.combined, npcs = 30, verbose = TRUE)

gbm.combined$condition = factor(gbm.combined$condition,levels=c("GBM.rec.PBMC","GBM.pembro.PBMC","HealthyDonor"))

#saveRDS(gbm.combined,file=paste(prefix, "scaled.PCA.rds", sep="_"))
#gbm.combined = readRDS(file=paste(prefix, "scaled.PCA.rds", sep="_"))
```

#Run UMAP for cluster visualization
```{r}
minDist = 0.2
spread1 = 2
NN = 20
seedUse = 122
epoch = 1000

prefix1 = paste(prefix,".MinD",minDist,".sprd",spread1,".NN",NN,".seed",seedUse,".ep",epoch,sep="")

gbm.combined <- RunUMAP(object = gbm.combined, reduction = "pca", dims = 1:30,min.dist = minDist, spread=spread1, n.neighbors=NN, seed.use = seedUse, n.epochs=epoch) 

outfile = paste(prefix1,"_UMAP.nUMI.png",sep="")
png(filename = outfile,width = 800, height = 800)
FeaturePlot(object = gbm.combined, features = c("nCount_RNA"), min.cutoff = "q9", pt.size = 2) #umi plot
dev.off()

outfile = paste(prefix1,"_UMAP.nGene.png",sep="")
png(filename = outfile,width = 800, height = 800)
FeaturePlot(object = gbm.combined, features = c("nFeature_RNA"), min.cutoff = "q9", pt.size = 2) #umi plot
dev.off()

outfile = paste(prefix1,"_UMAP.pctRibo.png",sep="")
png(filename = outfile,width = 800, height = 800)
FeaturePlot(object = gbm.combined, features = c("percent.ribo"), min.cutoff = "q9", pt.size = 2) #umi plot
dev.off()

outfile = paste(prefix1,"_UMAP.pctMito.png",sep="")
png(filename = outfile,width = 800, height = 800)
FeaturePlot(object = gbm.combined, features = c("percent.mt"), min.cutoff = "q9", pt.size = 2) #umi plot
dev.off()

outfile = paste(prefix1,"_UMAP.treatment.png",sep="")
png(filename = outfile,width = 800, height = 800)
DimPlot(object = gbm.combined, reduction = "umap", split.by = "condition", pt.size = 1, ncol=2)
dev.off()

#saveRDS(gbm.combined,file=paste(prefix1, ".rds", sep=""))
```

```{r}
DefaultAssay(gbm.combined) <- "RNA"

outfile = paste(prefix,"_UMAP.MainCellTypes1.png",sep="")
png(filename = outfile,width = 900, height = 1400)
FeaturePlot(object = gbm.combined, features = c("CD3D","CD8B","CD4","GZMB","CCR7","IL7R","CD14","HLA-DRA","S100A8","FCN1","FCGR3A","GNLY","PF4","CD79A","HLA-DRB1","HLA-DQA1","FCER1A","CLEC10A","IL3RA","CLEC4C","MKI67"), min.cutoff = "q9",  pt.size = 0.5, ncol=3, cols = c("lightgrey","red"))
dev.off()
```

#Cluster by PCA
```{r}
DefaultAssay(gbm.combined) <- "integrated"

gbm.combined <- FindNeighbors(object = gbm.combined, reduction = "pca", dims = 1:30, nn.method = "annoy", annoy.metric = "cosine", force.recalc = TRUE)
gbm.combined <- FindClusters(gbm.combined, resolution = 0.1)

outfile = paste(prefix,"_UMAP.Res0.1.png",sep="")
png(filename = outfile,width = 800, height = 800)
DimPlot(object = gbm.combined, reduction = "umap", group.by = "integrated_snn_res.0.1", label = TRUE, label.size = 8, pt.size = 1)#, cols = colors[1:16])
dev.off()

outfile = paste(prefix,"_UMAP.Res0.1.noLabel.png",sep="")
png(filename = outfile,width = 800, height = 800)
DimPlot(object = gbm.combined, reduction = "umap", group.by = "integrated_snn_res.0.1", label = FALSE, label.size = 8, pt.size = 1)#, cols = colors[1:16])
dev.off()

outfile = paste(prefix,"_UMAP.Res0.1.split.png",sep="")
png(filename = outfile,width = 800, height = 800)
DimPlot(object = gbm.combined, reduction = "umap", split.by = "integrated_snn_res.0.1", label = FALSE, pt.size = 0.5, ncol=3)#,cols = colors[1:16])
dev.off()
```

```{r}
DefaultAssay(gbm.combined) <- "RNA"
Idents(object = gbm.combined) <- "integrated_snn_res.0.1"
cluster.markers<- FindAllMarkers(object = gbm.combined, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.322)
outfile = paste(prefix,"_ClusterDiffGene.Res0.1.csv",sep="")
write.csv(cluster.markers, file=outfile)
```


```{r}
#assign each cluster cell type
Idents(object = gbm.combined) <- "integrated_snn_res.0.1"
current.cluster.ids <- c(0:10)
new.cluster.ids <- c("CD14+Mono","Tcell_LTB+IL7R+","T/NK","Tcell_GZMK+","LowRead",
                     "Bcell","CD16+Mono","Platelet","cDC2","Tcell_Proliferating","pDC")
Idents(object = gbm.combined) <- plyr::mapvalues(x = Idents(object = gbm.combined), from = current.cluster.ids, to = new.cluster.ids)

###### Draw cell type umap and calculate Percentage of each celltype in each sample ###########################################
gbm.combined@meta.data$celltype <- Idents(object = gbm.combined)
gbm.combined@meta.data$celltype <- factor(gbm.combined@meta.data$celltype, 
                                                 levels =
c("Tcell_LTB+IL7R+","Tcell_GZMK+","T/NK",
  "Tcell_Proliferating","CD14+Mono","CD16+Mono","cDC2",
  "pDC","Bcell","Platelet","LowRead")) 

saveRDS(gbm.combined,file=paste(prefix, "res.0.1.withAnnot.rds", sep="_"))
#gbm.combined = readRDS(file=paste(prefix, "res.0.1.withAnnot.rds", sep="_"))
```

```{r}
library(colorspace)
library(scales)
colorsCluster = c(qualitative_hcl(10),"lightgrey")

#show_col(colors)

outfile = paste(prefix,"_UMAP.Celltype.png",sep="")
png(filename = outfile,width = 800, height = 800)
DimPlot(object = gbm.combined, reduction = "umap", group.by = "celltype", label = TRUE, label.size = 8, pt.size = 1, cols = colorsCluster)
dev.off()

outfile = paste(prefix,"_UMAP.Celltype.noLabel.png",sep="")
png(filename = outfile,width = 800, height = 800)
DimPlot(object = gbm.combined, reduction = "umap", group.by = "celltype", label = FALSE, label.size = 8, pt.size = 1, cols = colorsCluster)
dev.off()
```

## Write the files into separate immune populations for subset analysis
```{r}
ids = rownames(subset(gbm.combined@meta.data,celltype %in% c("Tcell_LTB+IL7R+","Tcell_GZMK+","T/NK","Tcell_Proliferating")))
fileConn<-file(paste(prefix,".Lymphoid.ID.txt",sep=""))
writeLines(ids, fileConn)

ids = rownames(subset(gbm.combined@meta.data,celltype %in% c("CD14+Mono","CD16+Mono","cDC2")))
fileConn<-file(paste(prefix,".Myeloid.ID.txt",sep=""))
writeLines(ids, fileConn)
```
