```{r}
library(Seurat)
library(Matrix)
library(dplyr)
library(cowplot)

options(bitmapType='cairo') 
prefix = "Lymphoid.PBMC"
infile = "PBMC.all_res.0.1.withAnnot.rds"
id_file = "PBMC.all.Lymphoid.ID.txt"

source("AuxFunctions.R")
```

```{r}
ids <- as.character(read.table(id_file, header = FALSE)[,1])
gbm.all=readRDS(file=infile)
gbm.combined = subset(gbm.all, cells = ids)
rm(gbm.all)

gbm.combined@meta.data = gbm.combined@meta.data[!colnames(gbm.combined@meta.data) %in% c("integrated_snn_res.0.1","integrated_snn_res.0.3","seurat_clusters")]

DefaultAssay(object = gbm.combined) <- "RNA" 

#split the combined object into a list
ob.list1<-SplitObject(gbm.combined,split.by= "orig.ident")
ob.list = list()
objectlist = c()
condlist = c()
minCells =30

genesFiltered <- cleanGeneNames(rownames(gbm.combined))

for (i in 1:length(ob.list1)){

    test = ob.list1[[i]]

    test = subset(test, features = genesFiltered)
    dim(test)
    test = subset(test, subset = nFeature_RNA >= 100)
    dim(test)
    
  	if(ncol(test) >= minCells){ 
  	  
  	  m = test@meta.data
  	  print(m$orig.ident[[1]])
  	  test@meta.data = m[,1:12]
  	  test@reductions=list()
  	  test@commands=list()
  	  test@tools=list()
  	  test@assays$integrated=list()
  	  test <- NormalizeData(object = test, verbose = TRUE)
	  test  <- FindVariableFeatures(object = test , selection.method = "vst", nfeatures = 2000) 
	    
      ob.list = append(ob.list,test)
      objectlist = append(objectlist,m$orig.ident[[1]])
      condlist = append(condlist,as.character(m$condition[[1]]))
  	}
}

cellNumbers = sapply(ob.list, ncol)
table1 = data.frame(ID=objectlist,Cond = condlist, cellNumber = cellNumbers)
write.csv(table1,file=paste(prefix,"cellNumbers.csv",sep="."))
#saveRDS(ob.list,file=paste(prefix, "ObList.rds", sep="_"))

rm(gbm.combined)
rm(ob.list1)
```

```{r}
ob.list1 = ob.list[c(1:8)] #1/3 samples of each condition
ob.list2 = ob.list[c(9:15)] 

library(future)
library(future.apply)
plan("multiprocess", workers = 4)
options(future.globals.maxSize = 20 * 1024^3)

k.filterMax <- min(200, min(sapply(ob.list1, ncol)))
anchors1 <- FindIntegrationAnchors(object.list = ob.list1, k.filter = k.filterMax, anchor.features = 2000)
gbm.combined1 <- IntegrateData(anchorset = anchors1)
rm(anchors1)

k.filterMax <- min(200, min(sapply(ob.list2, ncol)))
anchors2 <- FindIntegrationAnchors(object.list = ob.list2, k.filter = k.filterMax, anchor.features = 2000)
gbm.combined2 <- IntegrateData(anchorset = anchors2)
rm(anchors2)

ob.list = list(gbm.combined1,gbm.combined2)
k.filterMax <- min(200, min(sapply(ob.list, ncol)))

library(future)
library(future.apply)
plan("multiprocess", workers = 4)
options(future.globals.maxSize = 20 * 1024^3)
anchors <- FindIntegrationAnchors(object.list = ob.list, k.filter = k.filterMax, anchor.features = 2000)
#saveRDS(anchors,file=paste(prefix, "anchors.rds", sep="_"))
rm(ob.list)
rm(gbm.combined1)
rm(gbm.combined2)

gc()

plan("multiprocess", workers = 1)
gbm.combined <- IntegrateData(anchorset = anchors)
DefaultAssay(object = gbm.combined) <- "integrated"
#saveRDS(gbm.combined,file=paste(prefix, "integrated.rds", sep="_"))
rm(anchors)
gc()

```
## Scale data
```{r}
dim(gbm.combined)

plan("multiprocess", workers = 4)
options(future.globals.maxSize = 20000 * 1024^2)
gbm.combined <- ScaleData(object = gbm.combined, verbose = TRUE, vars.to.regress = c("percent.mt","percent.ribo","nFeature_RNA","nCount_RNA","CC.Difference"))
gbm.combined <- RunPCA(object = gbm.combined, npcs = 30, verbose = TRUE)

gbm.combined$condition = factor(gbm.combined$condition,levels=c("GBM.rec.PBMC","GBM.pembro.PBMC","HealthyDonor"))
#saveRDS(gbm.combined,file=paste(prefix, "scaled.PCA.rds", sep="_"))
#gbm.combined = readRDS(file=paste(prefix, "scaled.PCA.rds", sep="_"))
```

```{r}
minDist = 0.2
spread1 = 5
NN = 20
seedUse = 222
epoch = 1000

prefix1 = paste(prefix,".MinD",minDist,".sprd",spread1,".NN",NN,".seed",seedUse,".ep",epoch,sep="")

gbm.combined <- RunUMAP(object = gbm.combined, reduction = "pca", dims = 1:30,min.dist = minDist, spread=spread1, n.neighbors=NN, seed.use = seedUse, n.epochs=epoch) #, min.dist = 0.1, n.neighbors=10, seed.use = 22, n.epochs=500)


outfile = paste(prefix1,"_UMAP.byBatch.png",sep="")
png(filename = outfile,width = 800, height = 1200)
DimPlot(object = gbm.combined, reduction = "umap", group.by = "condition", pt.size = 1)
dev.off()

outfile = paste(prefix1,"_UMAP.nUMI.png",sep="")
png(filename = outfile,width = 800, height = 800)
FeaturePlot(object = gbm.combined, features = c("nCount_RNA"), min.cutoff = "q9", pt.size = 2) #umi plot
dev.off()

outfile = paste(prefix1,"_UMAP.nGene.png",sep="")
png(filename = outfile,width = 800, height = 800)
FeaturePlot(object = gbm.combined, features = c("nFeature_RNA"), min.cutoff = "q9", pt.size = 2) #umi plot
dev.off()

outfile = paste(prefix1,"_UMAP.treatment.png",sep="")
png(filename = outfile,width = 800, height = 800)
DimPlot(object = gbm.combined, reduction = "umap", split.by = "condition", pt.size = 1, ncol=2)
dev.off()

#saveRDS(gbm.combined,file=paste(prefix1, "rds", sep="."))
#gbm.combined <- readRDS(file=paste(prefix1, "rds", sep="."))
```

```{r}
DefaultAssay(gbm.combined) <- "RNA"

outfile = paste(prefix,"_UMAP.MainCellTypes.png",sep="")
png(filename = outfile,width = 900, height = 1200)
FeaturePlot(object = gbm.combined, features = c("CD3D","CD8A","CD4","GZMA","GZMB","GZMH","GZMK","PRF1","IFNG","HLA-DQA1","PDCD1","CCR7","TCF7","CCL4","CCL5","IL7R","TIGIT","ICOS","CTLA4","FOXP3","MKI67"), min.cutoff = "q9",  pt.size = 0.5, ncol=3, cols = c("lightgrey","red"))
dev.off()

outfile = paste(prefix,"_UMAP.MainCellTypes2.png",sep="")
png(filename = outfile,width = 1200, height = 800)
FeaturePlot(object = gbm.combined, features = c("CD14","FCGR3A","XCL1","CD79A","CD160","ISG15","SELL","TRDC","CD274","CD69","ITGAE","CREM"), min.cutoff = "q9",  pt.size = 0.5, ncol=3, cols = c("lightgrey","red"))
dev.off()
```

```{r}
DefaultAssay(gbm.combined) <- "integrated"

gbm.combined <- FindNeighbors(object = gbm.combined, reduction = "pca", dims = 1:30, nn.method = "annoy", annoy.metric = "cosine", force.recalc = TRUE)
gbm.combined <- FindClusters(gbm.combined, resolution = 0.7)

colors = c("lightgrey","red","orange","yellow","green","blue","magenta","cyan","pink","brown","black","darkblue","purple","darkgreen","navyblue","maroon")

outfile = paste(prefix,"_UMAP.Res0.7.png",sep="")
png(filename = outfile,width = 800, height = 800)
DimPlot(object = gbm.combined, reduction = "umap", group.by = "integrated_snn_res.0.7", label = TRUE, label.size = 8, pt.size = 1)#,cols = colors[1:8])
dev.off()

```

```{r}
library(future)
library(future.apply)

##get the cluster markers
DefaultAssay(gbm.combined) <- "RNA"
Idents(object = gbm.combined) <- "integrated_snn_res.0.7"
plan("multiprocess", workers = 4)
options(future.globals.maxSize = 20000 * 1024^2)

cluster.markers<- FindAllMarkers(object = gbm.combined, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.322)
outfile = paste(prefix,"_ClusterDiffGene.Res0.7.log.322.csv",sep="")
write.csv(cluster.markers, file=outfile)
```


```{r}
Idents(object = gbm.combined) <- "integrated_snn_res.0.7"
current.cluster.ids <- c(0:22)

new.cluster.ids <- c("P3_CTL","P2_CD8+GZMK+","P1_CD8+GZMB+GZMH+","P3_CTL",
"P5_CD4+LTB+IL7R+","P5_CD4+LTB+IL7R+","P5_CD4+LTB+IL7R+","P7_CD4+Naive",
"P8_CD8+Naive","P13_gdT","P6_Treg","LowRead",
"P11_CD4-CD8-LTB+IL7R+","Platelet","P12_CD4-CD8-XCL1+XCL2+","LM_doublet",
"P4_Proliferating","P10_CD4+CD8+Naive","LM_doublet","P9_CD4-CD8-_GZMK+",
"B_cell","P14_ISGhi","Unknown")


Idents(object = gbm.combined) <- plyr::mapvalues(x = Idents(object = gbm.combined), from = current.cluster.ids, to = new.cluster.ids)

###### Percentage of each celltype in each sample ###########################################
gbm.combined@meta.data$celltype <- Idents(object = gbm.combined)
gbm.combined@meta.data$celltype <- factor(gbm.combined@meta.data$celltype, 
levels = c("P1_CD8+GZMB+GZMH+","P2_CD8+GZMK+","P3_CTL","P4_Proliferating","P5_CD4+LTB+IL7R+",
           "P6_Treg","P7_CD4+Naive","P8_CD8+Naive","P9_CD4-CD8-_GZMK+",
           "P10_CD4+CD8+Naive","P11_CD4-CD8-LTB+IL7R+","P12_CD4-CD8-XCL1+XCL2+","P13_gdT",
           "P14_ISGhi",
           "LM_doublet","B_cell","Platelet","LowRead","Unknown")) 

saveRDS(gbm.combined,file=paste(prefix, "res.0.7.withAnnot.rds", sep="_"))
#gbm.combined = readRDS(file=paste(prefix, "res.0.7.withAnnot.rds", sep="_"))
```

```{r}
colorsCluster <- c("orange","#882255","darkblue",
                   "darkgreen","#44AA99","#0072B2",
                   "#F0E442","#808000","cyan",
                   "magenta","pink","purple",
                   "brown","navyblue","plum",
                   "#FFE4B5","yellowgreen","lightgrey","lightgrey")

Idents(object = gbm.combined) <- "celltype"
DefaultAssay(gbm.combined) <- "RNA"

outfile = paste(prefix,"_UMAP.res.0.7.byCellType.png",sep="")
png(filename = outfile,width = 800, height = 800)
DimPlot(object = gbm.combined, reduction = "umap", group.by = "celltype", label = TRUE, label.size = 8, pt.size = 1,cols = colorsCluster)
dev.off()

outfile = paste(prefix,"_UMAP.res.0.7.noLabel.byCellType.png",sep="")
png(filename = outfile,width = 800, height = 800)
DimPlot(object = gbm.combined, reduction = "umap", group.by = "celltype", label = FALSE, label.size = 8, pt.size = 1,cols = colorsCluster)
dev.off()
```

For suppl table
```{r}
cluster.markers<- FindAllMarkers(object = gbm.combined, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.322)
outfile = paste(prefix,"_ClusterDiffGene.Res0.7.logFC.322.byCelltype.csv",sep="")
write.csv(cluster.markers, file=outfile)
```

```{r}
#output cell id suffix for TCR analysis of Trust4 
metadata = gbm.combined@meta.data
metadata$rownames = rownames(metadata)
idx = sub("^[^_]*_", "", metadata$rownames) #split the id by first underscore
metadata$idx = idx
table.new = unique(metadata[,c("orig.ident","condition","idx")])
write.table(table.new, file=paste(prefix,"CellIdxForTrust4.txt",sep="."), sep="\t")
```

```{r}
infile = "PBMC.all_res.0.1.withAnnot.rds"
gbm.all=readRDS(file=infile)

m.all <- gbm.all@meta.data
m.all$celltypeCombined <- m.all$celltype
m.all$cellID <- rownames(m.all)
rm(gbm.all)

prefix = "Lymphoid.PBMC"
gbm.lymphoid = readRDS(file=paste(prefix, "res.0.7.withAnnot.rds", sep="_"))

m1 <- gbm.lymphoid@meta.data
m1 <- m1[c("ID","condition","celltype")]

cols1 <- colnames(m1)
cols1[3] <- "celltype.Lymphoid"
colnames(m1) <- cols1
m1$cellID <- rownames(m1)
m1$celltypeCombined <- m1$celltype.Lymphoid

m.all1 <- m.all %>%
        left_join(m1,by = c("ID", "condition", "cellID")) %>%
        mutate(celltypeCombined = coalesce(celltypeCombined.y, celltypeCombined.x)) %>%
        select(-celltypeCombined.x, -celltypeCombined.y)

rm(gbm.lymphoid)

rownames(m.all1) <- m.all1$cellID
final_metadata <- m.all1 %>% 
                  select(-ID,-old.ident,-cellID,
                         -integrated_snn_res.0.1,
                         -integrated_snn_res.0.3,
                         -seurat_clusters)
write.csv(final_metadata,file="AllCell_withCellAnnot.PBMC.csv")
```






